import laamalif from "../Assets/huroof/Huroof Murakkabat/laamalif.png";

const huroofData = {
  Mufradat: [
    {
      id: 0,
      alphabet_name: "Alif",
      image: require("../Assets/huroof/Huroof Mufradat/alif.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 1,
      alphabet_name: "Baa",
      image: require("../Assets/huroof/Huroof Mufradat/baa.png"),
      video: require("../Assets/huroof/videos/baa.mp4"),
    },
    {
      id: 2,
      alphabet_name: "Taa",
      image: require("../Assets/huroof/Huroof Mufradat/taa.png"),
      video: require("../Assets/huroof/videos/taa.mp4"),
    },
    {
      id: 3,
      alphabet_name: "Saa",
      image: require("../Assets/huroof/Huroof Mufradat/saa.png"),
      video: require("../Assets/huroof/videos/saa.mp4"),
    },
    {
      id: 4,
      alphabet_name: "Jeem",
      image: require("../Assets/huroof/Huroof Mufradat/jeem.png"),
      video: require("../Assets/huroof/videos/jeem.mp4"),
    },
    {
      id: 5,
      alphabet_name: "Haa",
      image: require("../Assets/huroof/Huroof Mufradat/haa.png"),
      video: require("../Assets/huroof/videos/haa1.mp4"),
    },
    {
      id: 6,
      alphabet_name: "Kha",
      image: require("../Assets/huroof/Huroof Mufradat/kha.png"),
      video: require("../Assets/huroof/videos/kha.mp4"),
    },
    {
      id: 7,
      alphabet_name: "Daal",
      image: require("../Assets/huroof/Huroof Mufradat/daal.png"),
      video: require("../Assets/huroof/videos/daal.mp4"),
    },
    {
      id: 8,
      alphabet_name: "Zaal",
      image: require("../Assets/huroof/Huroof Mufradat/zaal.png"),
      video: require("../Assets/huroof/videos/zaal.mp4"),
    },
    {
      id: 9,
      alphabet_name: "Raa",
      image: require("../Assets/huroof/Huroof Mufradat/raa.png"),
      video: require("../Assets/huroof/videos/raa.mp4"),
    },
    {
      id: 10,
      alphabet_name: "Zaa",
      image: require("../Assets/huroof/Huroof Mufradat/zaa.png"),
      video: require("../Assets/huroof/videos/zaa.mp4"),
    },
    {
      id: 11,
      alphabet_name: "Seen",
      image: require("../Assets/huroof/Huroof Mufradat/seen.png"),
      video: require("../Assets/huroof/videos/seen.mp4"),
    },
    {
      id: 12,
      alphabet_name: "Sheen",
      image: require("../Assets/huroof/Huroof Mufradat/sheen.png"),
      video: require("../Assets/huroof/videos/sheen.mp4"),
    },
    {
      id: 13,
      alphabet_name: "Suad",
      image: require("../Assets/huroof/Huroof Mufradat/suad.png"),
      video: require("../Assets/huroof/videos/suad.mp4"),
    },
    {
      id: 14,
      alphabet_name: "Zuad",
      image: require("../Assets/huroof/Huroof Mufradat/zuad.png"),
      video: require("../Assets/huroof/videos/zuad.mp4"),
    },
    {
      id: 15,
      alphabet_name: "Tau",
      image: require("../Assets/huroof/Huroof Mufradat/tau.png"),
      video: require("../Assets/huroof/videos/tau.mp4"),
    },
    {
      id: 16,
      alphabet_name: "Zau",
      image: require("../Assets/huroof/Huroof Mufradat/zau.png"),
      video: require("../Assets/huroof/videos/zau.mp4"),
    },
    {
      id: 17,
      alphabet_name: "Aeeen",
      image: require("../Assets/huroof/Huroof Mufradat/aeeen.png"),
      video: require("../Assets/huroof/videos/aeeen.mp4"),
    },
    {
      id: 18,
      alphabet_name: "Gaeen",
      image: require("../Assets/huroof/Huroof Mufradat/gaeen.png"),
      video: require("../Assets/huroof/videos/gaeen.mp4"),
    },
    {
      id: 19,
      alphabet_name: "Faa",
      image: require("../Assets/huroof/Huroof Mufradat/faa.png"),
      video: require("../Assets/huroof/videos/faa.mp4"),
    },
    {
      id: 20,
      alphabet_name: "Qaaf",
      image: require("../Assets/huroof/Huroof Mufradat/qaaf.png"),
      video: require("../Assets/huroof/videos/qaaf.mp4"),
    },
    {
      id: 21,
      alphabet_name: "Kaaf",
      image: require("../Assets/huroof/Huroof Mufradat/kaaf.png"),
      video: require("../Assets/huroof/videos/kaaf.mp4"),
    },
    {
      id: 22,
      alphabet_name: "Laam",
      image: require("../Assets/huroof/Huroof Mufradat/laam.png"),
      video: require("../Assets/huroof/videos/laam.mp4"),
    },
    {
      id: 23,
      alphabet_name: "Meem",
      image: require("../Assets/huroof/Huroof Mufradat/meem.png"),
      video: require("../Assets/huroof/videos/meem.mp4"),
    },
    {
      id: 24,
      alphabet_name: "Noon",
      image: require("../Assets/huroof/Huroof Mufradat/noon.png"),
      video: require("../Assets/huroof/videos/noon.mp4"),
    },
    {
      id: 25,
      alphabet_name: "Wow",
      image: require("../Assets/huroof/Huroof Mufradat/wow.png"),
      video: require("../Assets/huroof/videos/wow.mp4"),
    },
    {
      id: 26,
      alphabet_name: "Hamza",
      image: require("../Assets/huroof/Huroof Mufradat/hamza.png"),
      video: require("../Assets/huroof/videos/aeeen.mp4"),
    },
    {
      id: 27,
      alphabet_name: "Haa1",
      image: require("../Assets/huroof/Huroof Mufradat/haa1.png"),
      video: require("../Assets/huroof/videos/haa1.mp4"),
    },
    {
      id: 28,
      alphabet_name: "Bari_ya",
      image: require("../Assets/huroof/Huroof Mufradat/bari_ya.png"),
      video: require("../Assets/huroof/videos/bari_ya.mp4"),
    },
    {
      id: 29,
      alphabet_name: "Choti_ya",
      image: require("../Assets/huroof/Huroof Mufradat/choti_ya.png"),
      video: require("../Assets/huroof/videos/choti_ya.mp4"),
    },
  ],
  Murakkabat: [
    {
      id: 30,
      alphabet_name: "Aliff",
      image: require("../Assets/huroof/Huroof Mufradat/alif.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 31,
      alphabet_name: "Lam Alif",
      image: laamalif,
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 32,
      alphabet_name: "Laam Alif3",
      image: require("../Assets/huroof/Huroof Murakkabat/laamalif3.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 33,
      alphabet_name: "Baa Alif",
      image: require("../Assets/huroof/Huroof Murakkabat/baaalif.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 34,
      alphabet_name: "Laam Alif2",
      image: require("../Assets/huroof/Huroof Murakkabat/laamalif2.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 35,
      alphabet_name: "Laam",
      image: require("../Assets/huroof/Huroof Murakkabat/laamalif.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 36,
      alphabet_name: "Laam Alif1",
      image: require("../Assets/huroof/Huroof Murakkabat/laamalif1.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 37,
      alphabet_name: "Laam Haa",
      image: require("../Assets/huroof/Huroof Murakkabat/laamhaa.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 38,
      alphabet_name: "Laam Alif4",
      image: require("../Assets/huroof/Huroof Murakkabat/laamalif4.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 39,
      alphabet_name: "Baa Laam Baa",
      image: require("../Assets/huroof/Huroof Murakkabat/baalaambaa.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 40,
      alphabet_name: "Kaaf",
      image: require("../Assets/huroof/Huroof Murakkabat/kaaf.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 41,
      alphabet_name: "Kaaf1",
      image: require("../Assets/huroof/Huroof Murakkabat/kaaf1.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 42,
      alphabet_name: "Ka Baa",
      image: require("../Assets/huroof/Huroof Murakkabat/kabaa.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 43,
      alphabet_name: "Kaaf Baa",
      image: require("../Assets/huroof/Huroof Murakkabat/kaafbaa.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 44,
      alphabet_name: "Qaaf Alif",
      image: require("../Assets/huroof/Huroof Murakkabat/qaafalif.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 45,
      alphabet_name: "Qaaf Alif1",
      image: require("../Assets/huroof/Huroof Murakkabat/qaafalif1.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 46,
      alphabet_name: "Ba Ka Taa",
      image: require("../Assets/huroof/Huroof Murakkabat/bakataa.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 47,
      alphabet_name: "Ta Ka Saa",
      image: require("../Assets/huroof/Huroof Murakkabat/takasaa.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 48,
      alphabet_name: "Baa",
      image: require("../Assets/huroof/Huroof Murakkabat/baa.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 49,
      alphabet_name: "Taa",
      image: require("../Assets/huroof/Huroof Murakkabat/taa.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 50,
      alphabet_name: "Saa",
      image: require("../Assets/huroof/Huroof Murakkabat/saa.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 51,
      alphabet_name: "Noon",
      image: require("../Assets/huroof/Huroof Murakkabat/noon.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 52,
      alphabet_name: "Yaa",
      image: require("../Assets/huroof/Huroof Murakkabat/yaa.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 53,
      alphabet_name: "Baa Alif",
      image: require("../Assets/huroof/Huroof Murakkabat/baaalif.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 54,
      alphabet_name: "Noon Alif",
      image: require("../Assets/huroof/Huroof Murakkabat/noonalif.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 55,
      alphabet_name: "Taa Alif",
      image: require("../Assets/huroof/Huroof Murakkabat/taaalif.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 56,
      alphabet_name: "Yaa Alif",
      image: require("../Assets/huroof/Huroof Murakkabat/yaaalif.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 57,
      alphabet_name: "Saa Alif",
      image: require("../Assets/huroof/Huroof Murakkabat/saaalif.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 58,
      alphabet_name: "Ba Seen",
      image: require("../Assets/huroof/Huroof Murakkabat/baseen.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 59,
      alphabet_name: "Yaa Seen",
      image: require("../Assets/huroof/Huroof Murakkabat/yaaseen.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 60,
      alphabet_name: "Noon Seen",
      image: require("../Assets/huroof/Huroof Murakkabat/noonseen.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 61,
      alphabet_name: "Ta Seen",
      image: require("../Assets/huroof/Huroof Murakkabat/taseen.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 62,
      alphabet_name: "Sa Seen",
      image: require("../Assets/huroof/Huroof Murakkabat/saseen.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 63,
      alphabet_name: "Saa Jeem",
      image: require("../Assets/huroof/Huroof Murakkabat/saajeem.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 64,
      alphabet_name: "Taa Haa",
      image: require("../Assets/huroof/Huroof Murakkabat/taahaa.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 65,
      alphabet_name: "Noon Kha",
      image: require("../Assets/huroof/Huroof Murakkabat/noonkha.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 66,
      alphabet_name: "Ya Haa",
      image: require("../Assets/huroof/Huroof Murakkabat/yahaa.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 67,
      alphabet_name: "Baa Jeem",
      image: require("../Assets/huroof/Huroof Murakkabat/baajeem.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 68,
      alphabet_name: "Ya Meem",
      image: require("../Assets/huroof/Huroof Murakkabat/yameem.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 69,
      alphabet_name: "Ba Meem",
      image: require("../Assets/huroof/Huroof Murakkabat/bameem.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 70,
      alphabet_name: "Noon Meem",
      image: require("../Assets/huroof/Huroof Murakkabat/noonmeem.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 71,
      alphabet_name: "Ta Meem1",
      image: require("../Assets/huroof/Huroof Murakkabat/tameem1.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 72,
      alphabet_name: "Saa Meem",
      image: require("../Assets/huroof/Huroof Murakkabat/saameem.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 73,
      alphabet_name: "Ba Yaa",
      image: require("../Assets/huroof/Huroof Murakkabat/bayaa.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 74,
      alphabet_name: "Ya Yaa",
      image: require("../Assets/huroof/Huroof Murakkabat/yayaa.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 75,
      alphabet_name: "Noon Yaa",
      image: require("../Assets/huroof/Huroof Murakkabat/noonyaa.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 76,
      alphabet_name: "Ta Yaa",
      image: require("../Assets/huroof/Huroof Murakkabat/tayaa.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 77,
      alphabet_name: "Sa Yaa",
      image: require("../Assets/huroof/Huroof Murakkabat/sayaa.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 78,
      alphabet_name: "Noon Ba Laam",
      image: require("../Assets/huroof/Huroof Murakkabat/noonbalaam.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 79,
      alphabet_name: "Ta Noon Laam",
      image: require("../Assets/huroof/Huroof Murakkabat/tanoonlaam.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 80,
      alphabet_name: "Ba Ya Laam",
      image: require("../Assets/huroof/Huroof Murakkabat/bayalaam.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 81,
      alphabet_name: "Ya Ta Laam",
      image: require("../Assets/huroof/Huroof Murakkabat/yatalaam.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 82,
      alphabet_name: "Sa Sa Laam",
      image: require("../Assets/huroof/Huroof Murakkabat/sasalaam.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 83,
      alphabet_name: "Noon Ba Noon",
      image: require("../Assets/huroof/Huroof Murakkabat/noonbanoon.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 84,
      alphabet_name: "Ba Noon Noon",
      image: require("../Assets/huroof/Huroof Murakkabat/banoonoon.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 85,
      alphabet_name: "Ta Ya Noon",
      image: require("../Assets/huroof/Huroof Murakkabat/tayanoon.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 86,
      alphabet_name: "Ya Ta Noon",
      image: require("../Assets/huroof/Huroof Murakkabat/yatanoon.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 87,
      alphabet_name: "Sa Sa Noon",
      image: require("../Assets/huroof/Huroof Murakkabat/sasanoon.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 88,
      alphabet_name: "Jeem",
      image: require("../Assets/huroof/Huroof Murakkabat/jeem.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 89,
      alphabet_name: "Ha",
      image: require("../Assets/huroof/Huroof Murakkabat/ha.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 90,
      alphabet_name: "Kha",
      image: require("../Assets/huroof/Huroof Murakkabat/kha.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 91,
      alphabet_name: "Ha Saa",
      image: require("../Assets/huroof/Huroof Murakkabat/hasaa.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 92,
      alphabet_name: "Kha Baa",
      image: require("../Assets/huroof/Huroof Murakkabat/khabaa.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 93,
      alphabet_name: "Jeem Taa",
      image: require("../Assets/huroof/Huroof Murakkabat/jeemtaa.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 94,
      alphabet_name: "Ta Ha Taa",
      image: require("../Assets/huroof/Huroof Murakkabat/tahataa.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 95,
      alphabet_name: "Ya Jeem Baa",
      image: require("../Assets/huroof/Huroof Murakkabat/yajeembaa.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 96,
      alphabet_name: "Ba Kha Taa",
      image: require("../Assets/huroof/Huroof Murakkabat/bakhataa.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 97,
      alphabet_name: "Taa1",
      image: require("../Assets/huroof/Huroof Murakkabat/taa1.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 98,
      alphabet_name: "Haa1",
      image: require("../Assets/huroof/Huroof Murakkabat/haa1.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 99,
      alphabet_name: "Ba Taa",
      image: require("../Assets/huroof/Huroof Murakkabat/bataa.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 100,
      alphabet_name: "Ya Haa1",
      image: require("../Assets/huroof/Huroof Murakkabat/yahaa1.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 101,
      alphabet_name: "Ta Haa",
      image: require("../Assets/huroof/Huroof Murakkabat/tahaa.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 102,
      alphabet_name: "Noon Ta",
      image: require("../Assets/huroof/Huroof Murakkabat/noonta.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 103,
      alphabet_name: "Haa",
      image: require("../Assets/huroof/Huroof Murakkabat/haa.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 104,
      alphabet_name: "Ya Ha Baa",
      image: require("../Assets/huroof/Huroof Murakkabat/yahabaa.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 105,
      alphabet_name: "Ba Ha Alif",
      image: require("../Assets/huroof/Huroof Murakkabat/bahaalif.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 106,
      alphabet_name: "Ba Ha Meem",
      image: require("../Assets/huroof/Huroof Murakkabat/bahameem.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 107,
      alphabet_name: "Daal",
      image: require("../Assets/huroof/Huroof Murakkabat/daal.png"),
      video: require("../Assets/huroof/videos/daal.mp4"),
    },
    {
      id: 108,
      alphabet_name: "Zaal",
      image: require("../Assets/huroof/Huroof Murakkabat/zaal.png"),
      video: require("../Assets/huroof/videos/zaal.mp4"),
    },
    {
      id: 109,
      alphabet_name: "Jeem Daal",
      image: require("../Assets/huroof/Huroof Murakkabat/jeemdaal.png"),
      video: require("../Assets/huroof/videos/zaal.mp4"),
    },
    {
      id: 110,
      alphabet_name: "Kha Zaa",
      image: require("../Assets/huroof/Huroof Murakkabat/khazaa.png"),
      video: require("../Assets/huroof/videos/zaal.mp4"),
    },
    {
      id: 111,
      alphabet_name: "Raa",
      image: require("../Assets/huroof/Huroof Murakkabat/raa.png"),
      video: require("../Assets/huroof/videos/raa.mp4"),
    },
    {
      id: 112,
      alphabet_name: "Zaa",
      image: require("../Assets/huroof/Huroof Murakkabat/zaa.png"),
      video: require("../Assets/huroof/videos/zaa.mp4"),
    },
    {
      id: 113,
      alphabet_name: "Jeem Raa",
      image: require("../Assets/huroof/Huroof Murakkabat/jeemraa.png"),
      video: require("../Assets/huroof/videos/raa.mp4"),
    },
    {
      id: 114,
      alphabet_name: "Kha Zaa1",
      image: require("../Assets/huroof/Huroof Murakkabat/khazaa1.png"),
      video: require("../Assets/huroof/videos/raa.mp4"),
    },
    {
      id: 115,
      alphabet_name: "Raa1",
      image: require("../Assets/huroof/Huroof Murakkabat/raa1.png"),
      video: require("../Assets/huroof/videos/raa.mp4"),
    },
    {
      id: 116,
      alphabet_name: "Zaa1",
      image: require("../Assets/huroof/Huroof Murakkabat/zaa1.png"),
      video: require("../Assets/huroof/videos/zaa.mp4"),
    },
    {
      id: 117,
      alphabet_name: "Ya Raa",
      image: require("../Assets/huroof/Huroof Murakkabat/yaraa.png"),
      video: require("../Assets/huroof/videos/raa.mp4"),
    },
    {
      id: 118,
      alphabet_name: "Ta Zaa",
      image: require("../Assets/huroof/Huroof Murakkabat/tazaa.png"),
      video: require("../Assets/huroof/videos/raa.mp4"),
    },
    {
      id: 119,
      alphabet_name: "Seen",
      image: require("../Assets/huroof/Huroof Murakkabat/seen.png"),
      video: require("../Assets/huroof/videos/seen.mp4"),
    },
    {
      id: 120,
      alphabet_name: "Sheen",
      image: require("../Assets/huroof/Huroof Murakkabat/sheen.png"),
      video: require("../Assets/huroof/videos/sheen.mp4"),
    },
    {
      id: 121,
      alphabet_name: "Seen Laam",
      image: require("../Assets/huroof/Huroof Murakkabat/seenlaam.png"),
      video: require("../Assets/huroof/videos/seen.mp4"),
    },
    {
      id: 122,
      alphabet_name: "Sheen Laam",
      image: require("../Assets/huroof/Huroof Murakkabat/sheenlaam.png"),
      video: require("../Assets/huroof/videos/seen.mp4"),
    },
    {
      id: 123,
      alphabet_name: "Suaad",
      image: require("../Assets/huroof/Huroof Murakkabat/suaad.png"),
      video: require("../Assets/huroof/videos/seen.mp4"),
    },
    {
      id: 124,
      alphabet_name: "Zuad",
      image: require("../Assets/huroof/Huroof Murakkabat/zuad.png"),
      video: require("../Assets/huroof/videos/seen.mp4"),
    },
    {
      id: 125,
      alphabet_name: "Tauu",
      image: require("../Assets/huroof/Huroof Murakkabat/tauu.png"),
      video: require("../Assets/huroof/videos/seen.mp4"),
    },
    {
      id: 126,
      alphabet_name: "Zuaa",
      image: require("../Assets/huroof/Huroof Murakkabat/zuaa.png"),
      video: require("../Assets/huroof/videos/seen.mp4"),
    },
    {
      id: 127,
      alphabet_name: "Suad Baa",
      image: require("../Assets/huroof/Huroof Murakkabat/suadbaa.png"),
      video: require("../Assets/huroof/videos/seen.mp4"),
    },
    {
      id: 128,
      alphabet_name: "Tuaba",
      image: require("../Assets/huroof/Huroof Murakkabat/tauba.png"),
      video: require("../Assets/huroof/videos/seen.mp4"),
    },
    {
      id: 129,
      alphabet_name: "Zuad Alif",
      image: require("../Assets/huroof/Huroof Murakkabat/zuadalif.png"),
      video: require("../Assets/huroof/videos/seen.mp4"),
    },
    {
      id: 130,
      alphabet_name: "Zua Alif",
      image: require("../Assets/huroof/Huroof Murakkabat/zuaalif.png"),
      video: require("../Assets/huroof/videos/seen.mp4"),
    },
    {
      id: 131,
      alphabet_name: "Aaeen",
      image: require("../Assets/huroof/Huroof Murakkabat/aaeen.png"),
      video: require("../Assets/huroof/videos/aeeen.mp4"),
    },
    {
      id: 132,
      alphabet_name: "Gaeen",
      image: require("../Assets/huroof/Huroof Murakkabat/gaeen.png"),
      video: require("../Assets/huroof/videos/gaeen.mp4"),
    },
    {
      id: 133,
      alphabet_name: "Hamza",
      image: require("../Assets/huroof/Huroof Murakkabat/hamza.png"),
      video: require("../Assets/huroof/videos/gaeen.mp4"),
    },
    {
      id: 134,
      alphabet_name: "Aeen Za",
      image: require("../Assets/huroof/Huroof Murakkabat/aeenza.png"),
      video: require("../Assets/huroof/videos/gaeen.mp4"),
    },
    {
      id: 135,
      alphabet_name: "Gaeen Ra",
      image: require("../Assets/huroof/Huroof Murakkabat/gaeenra.png"),
      video: require("../Assets/huroof/videos/gaeen.mp4"),
    },
    {
      id: 136,
      alphabet_name: "Suad Aeen",
      image: require("../Assets/huroof/Huroof Murakkabat/suadaeen.png"),
      video: require("../Assets/huroof/videos/gaeen.mp4"),
    },
    {
      id: 137,
      alphabet_name: "Zuad Gaeen",
      image: require("../Assets/huroof/Huroof Murakkabat/zuadgaeen.png"),
      video: require("../Assets/huroof/videos/gaeen.mp4"),
    },
    {
      id: 138,
      alphabet_name: "Ba Aeen Daal",
      image: require("../Assets/huroof/Huroof Murakkabat/baaeendaal.png"),
      video: require("../Assets/huroof/videos/gaeen.mp4"),
    },
    {
      id: 139,
      alphabet_name: "Ta Ga Zaa",
      image: require("../Assets/huroof/Huroof Murakkabat/tagazaa.png"),
      video: require("../Assets/huroof/videos/gaeen.mp4"),
    },
    {
      id: 140,
      alphabet_name: "Hamzaaa",
      image: require("../Assets/huroof/Huroof Murakkabat/hamzaaa.png"),
      video: require("../Assets/huroof/videos/gaeen.mp4"),
    },
    {
      id: 141,
      alphabet_name: "Aeen Wow",
      image: require("../Assets/huroof/Huroof Murakkabat/aeenwow.png"),
      video: require("../Assets/huroof/videos/gaeen.mp4"),
    },
    {
      id: 142,
      alphabet_name: "Aeen Yaa",
      image: require("../Assets/huroof/Huroof Murakkabat/aeenyaa.png"),
      video: require("../Assets/huroof/videos/gaeen.mp4"),
    },
    {
      id: 143,
      alphabet_name: "Faa",
      image: require("../Assets/huroof/Huroof Murakkabat/faa.png"),
      video: require("../Assets/huroof/videos/faa.mp4"),
    },
    {
      id: 144,
      alphabet_name: "Qaaf",
      image: require("../Assets/huroof/Huroof Murakkabat/qaaf.png"),
      video: require("../Assets/huroof/videos/qaaf.mp4"),
    },
    {
      id: 145,
      alphabet_name: "Wow",
      image: require("../Assets/huroof/Huroof Murakkabat/wow.png"),
      video: require("../Assets/huroof/videos/wow.mp4"),
    },
    {
      id: 146,
      alphabet_name: "Qaaf Wow",
      image: require("../Assets/huroof/Huroof Murakkabat/qaafwow.png"),
      video: require("../Assets/huroof/videos/wow.mp4"),
    },
    {
      id: 147,
      alphabet_name: "Fa Wow",
      image: require("../Assets/huroof/Huroof Murakkabat/fawow.png"),
      video: require("../Assets/huroof/videos/wow.mp4"),
    },
    {
      id: 148,
      alphabet_name: "Fa Qaaf Laam",
      image: require("../Assets/huroof/Huroof Murakkabat/faqaaflaam.png"),
      video: require("../Assets/huroof/videos/wow.mp4"),
    },
    {
      id: 149,
      alphabet_name: "Qaaf Fa Laam",
      image: require("../Assets/huroof/Huroof Murakkabat/qaaffalaam.png"),
      video: require("../Assets/huroof/videos/wow.mp4"),
    },
    {
      id: 150,
      alphabet_name: "Ya Faa",
      image: require("../Assets/huroof/Huroof Murakkabat/yafaa.png"),
      video: require("../Assets/huroof/videos/wow.mp4"),
    },
    {
      id: 151,
      alphabet_name: "Meem",
      image: require("../Assets/huroof/Huroof Murakkabat/meem.png"),
      video: require("../Assets/huroof/videos/meem.mp4"),
    },
    {
      id: 152,
      alphabet_name: "Ha Meem",
      image: require("../Assets/huroof/Huroof Murakkabat/hameem.png"),
      video: require("../Assets/huroof/videos/wow.mp4"),
    },
    {
      id: 153,
      alphabet_name: "Laam Meem",
      image: require("../Assets/huroof/Huroof Murakkabat/laameem.png"),
      video: require("../Assets/huroof/videos/wow.mp4"),
    },
    {
      id: 154,
      alphabet_name: "Ta Meem",
      image: require("../Assets/huroof/Huroof Murakkabat/tameem.png"),
      video: require("../Assets/huroof/videos/wow.mp4"),
    },
    {
      id: 155,
      alphabet_name: "Ta Meem Taa",
      image: require("../Assets/huroof/Huroof Murakkabat/tameemtaa.png"),
      video: require("../Assets/huroof/videos/wow.mp4"),
    },
  ],
  Murqattaat: [
    {
      id: 156,
      alphabet_name: "Alif Laam Meem",
      image: require("../Assets/huroof/Huroof Muraqattat/aliflaammeem.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    ,
    {
      id: 157,
      alphabet_name: "Alif Laam Meem Suad",
      image: require("../Assets/huroof/Huroof Muraqattat/aliflaameemsuad.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 158,
      alphabet_name: "Tua Seen Meem",
      image: require("../Assets/huroof/Huroof Muraqattat/tuaseenmeem.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 159,
      alphabet_name: "Tua Seen",
      image: require("../Assets/huroof/Huroof Muraqattat/tauseen.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 160,
      alphabet_name: "Alif Laam Raa",
      image: require("../Assets/huroof/Huroof Muraqattat/aliflaamra.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 161,
      alphabet_name: "Alif Laam Meem Raa",
      image: require("../Assets/huroof/Huroof Muraqattat/aliflaameemra.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 162,
      alphabet_name: "Yaa Seen",
      image: require("../Assets/huroof/Huroof Muraqattat/yaseen.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 163,
      alphabet_name: "Suad",
      image: require("../Assets/huroof/Huroof Muraqattat/suad.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 164,
      alphabet_name: "Kaaf Haa Yaa Aeen Suad",
      image: require("../Assets/huroof/Huroof Muraqattat/kaafhayaaeensuad.png"),
      video: require("../Assets/huroof/videos/alif.mp4"),
    },
    {
      id: 165,
      alphabet_name: "Tua Haa",
      image: require("../Assets/huroof/Huroof Muraqattat/tauha.png"),
      video: require("../Assets/huroof/videos/kaaf.mp4"),
    },
    {
      id: 166,
      alphabet_name: "Ha Meem",
      image: require("../Assets/huroof/Huroof Muraqattat/hameem.png"),
      video: require("../Assets/huroof/videos/kaaf.mp4"),
    },
    {
      id: 167,
      alphabet_name: "Ha Meem Aeen Seen Qaaf",
      image: require("../Assets/huroof/Huroof Muraqattat/hameem_aeenseenqaaf.png"),
      video: require("../Assets/huroof/videos/kaaf.mp4"),
    },
    {
      id: 168,
      alphabet_name: "Qaaf",
      image: require("../Assets/huroof/Huroof Muraqattat/qaaf.png"),
      video: require("../Assets/huroof/videos/qaaf.mp4"),
    },
    {
      id: 169,
      alphabet_name: "Noon",
      image: require("../Assets/huroof/Huroof Muraqattat/noon.png"),
      video: require("../Assets/huroof/videos/noon.mp4"),
    },
  ],
};

export default huroofData;
